name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - run: uv lock --check
      - run: uv sync --frozen --extra test
      - run: uv run python -m pytest
      - run: uv build
